import { LocalizationType, type CellLibraryDefinition } from "./hexTile";

export const CellLibrary: CellLibraryDefinition = {
  [LocalizationType.House]: {
    sprite: "modern_house.png",
    localizationType: LocalizationType.House,
    walkable: true,
    numberMin: 0,
    numberMax: 1,
  },
  [LocalizationType.Pharmacy]: {
    sprite: "modern_shop.png",
    localizationType: LocalizationType.Pharmacy,
    walkable: true,
    numberMin: 1,
    numberMax: 1,
  },
  [LocalizationType.PoliceStation]: {
    sprite: "western_sheriff.png",
    localizationType: LocalizationType.PoliceStation,
    walkable: true,
    numberMin: 1,
    numberMax: 1,
  },
  [LocalizationType.Hardware]: {
    sprite: "mill_storage.png",
    localizationType: LocalizationType.Hardware,
    walkable: true,
    numberMin: 1,
    numberMax: 1,
  },
  [LocalizationType.Factory]: {
    sprite: "mill_factory.png",
    localizationType: LocalizationType.Factory,
    walkable: true,
    numberMin: 1,
    numberMax: 1,
  },
  [LocalizationType.Hospital]: {
    sprite: "modern_largeBuilding.png",
    localizationType: LocalizationType.Hospital,
    walkable: true,
    numberMin: 1,
    numberMax: 1,
  },
  [LocalizationType.Workshop]: {
    sprite: "medieval_blacksmith.png",
    localizationType: LocalizationType.Workshop,
    walkable: true,
    numberMin: 1,
    numberMax: 1,
  },
  [LocalizationType.Security]: {
    sprite: "military_turretMedium.png",
    localizationType: LocalizationType.Security,
    walkable: true,
    numberMin: 1,
    numberMax: 1,
  },
  [LocalizationType.GasStation]: {
    sprite: "modern_petrol.png",
    localizationType: LocalizationType.GasStation,
    walkable: true,
    numberMin: 1,
    numberMax: 1,
  },
  [LocalizationType.Market]: {
    sprite: "modern_cornerShop.png",
    localizationType: LocalizationType.Market,
    walkable: true,
    numberMin: 1,
    numberMax: 1,
  },
  [LocalizationType.Restaurant]: {
    sprite: "western_saloon.png",
    localizationType: LocalizationType.Restaurant,
    walkable: true,
    numberMin: 1,
    numberMax: 1,
  },
  [LocalizationType.Road]: {
    sprite: "dirt_02.png",
    localizationType: LocalizationType.Road,
    walkable: true,
    numberMin: 0,
    numberMax: -1,
  },
  [LocalizationType.Path]: {
    sprite: "grass_02.png",
    localizationType: LocalizationType.Path,
    walkable: true,
    numberMin: 0,
    numberMax: -1,
  },
  [LocalizationType.Alley]: {
    sprite: "stone_04.png",
    localizationType: LocalizationType.Alley,
    walkable: true,
    numberMin: 0,
    numberMax: -1,
  },
};
