import { ActionLibrary } from "./ActionLibrary";
import { LocalizationType, type CellLibraryDefinition } from "./hexTile";

export const CellLibrary: CellLibraryDefinition = {
  [LocalizationType.House]: {
    sprite: "modern_house.png",
    localizationType: LocalizationType.House,
    specialActionIds: [ActionLibrary.look_through_window.id],
    walkable: true,
    numberMin: 0,
    numberMax: 1,
    startingItems: [
      { itemId: "drink", quantity: 4 },
      { itemId: "food", quantity: 3 },
      { itemId: "bandage", quantity: 2 },
      { itemId: "medicine", quantity: 1 },
      { itemId: "bandolier", quantity: 2 },
      { itemId: "knife", quantity: 3 },
      { itemId: "bat", quantity: 2 },
      { itemId: "axe", quantity: 2 },
      { itemId: "arrow", quantity: 4 },
      { itemId: "chemical_weapon", quantity: 1 },
      { itemId: "fuel", quantity: 3 },
      { itemId: "nails", quantity: 2 },
      { itemId: "poison", quantity: 3 },
      { itemId: "lockpick", quantity: 2 },
      { itemId: "binoculars", quantity: 1 },
      { itemId: "walkie_talkie", quantity: 1 },
      { itemId: "zarkans", quantity: 4 },
    ],
  },
  [LocalizationType.Pharmacy]: {
    sprite: "modern_shop.png",
    localizationType: LocalizationType.Pharmacy,
    specialActionIds: [ActionLibrary.look_through_window.id],
    walkable: true,
    numberMin: 1,
    numberMax: 1,
    startingItems: [
      { itemId: "drink", quantity: 4 },
      { itemId: "food", quantity: 1 },
      { itemId: "bandage", quantity: 5 },
      { itemId: "medicine", quantity: 2 },
      { itemId: "antidote", quantity: 7 },
      { itemId: "spike", quantity: 3 },
      { itemId: "chemical_weapon", quantity: 1 },
      { itemId: "poison", quantity: 2 },
      { itemId: "vaccine", quantity: 1 },
      { itemId: "walkie_talkie", quantity: 1 },
      { itemId: "zarkans", quantity: 3 },
    ],
  },
  [LocalizationType.PoliceStation]: {
    sprite: "western_sheriff.png",
    localizationType: LocalizationType.PoliceStation,
    walkable: true,
    numberMin: 1,
    numberMax: 1,
    startingItems: [
      { itemId: "drink", quantity: 1 },
      { itemId: "bandage", quantity: 1 },
      { itemId: "bulletproof_vest", quantity: 3 },
      { itemId: "pistol", quantity: 4 },
      { itemId: "bullet", quantity: 9 },
      { itemId: "trap", quantity: 2 },
      { itemId: "c4", quantity: 3 },
      { itemId: "fuel", quantity: 3 },
      { itemId: "walkie_talkie", quantity: 1 },
      { itemId: "zarkans", quantity: 2 },
    ],
  },
  [LocalizationType.Hardware]: {
    sprite: "mill_storage.png",
    localizationType: LocalizationType.Hardware,
    walkable: true,
    numberMin: 1,
    numberMax: 1,
    startingItems: [
      { itemId: "wood", quantity: 4 },
      { itemId: "spike", quantity: 5 },
      { itemId: "knife", quantity: 2 },
      { itemId: "axe", quantity: 2 },
      { itemId: "chainsaw", quantity: 2 },
      { itemId: "harpoon", quantity: 2 },
      { itemId: "nails", quantity: 5 },
      { itemId: "lockpick", quantity: 3 },
      { itemId: "binoculars", quantity: 2 },
      { itemId: "walkie_talkie", quantity: 1 },
      { itemId: "zarkans", quantity: 3 },
    ],
  },
  [LocalizationType.Factory]: {
    sprite: "mill_factory.png",
    localizationType: LocalizationType.Factory,
    walkable: true,
    numberMin: 1,
    numberMax: 1,
    startingItems: [
      { itemId: "drink", quantity: 1 },
      { itemId: "bulletproof_vest", quantity: 1 },
      { itemId: "wood", quantity: 3 },
      { itemId: "spike", quantity: 3 },
      { itemId: "bat", quantity: 2 },
      { itemId: "axe", quantity: 3 },
      { itemId: "harpoon", quantity: 4 },
      { itemId: "chemical_weapon", quantity: 2 },
      { itemId: "trap", quantity: 4 },
      { itemId: "c4", quantity: 4 },
      { itemId: "nails", quantity: 2 },
      { itemId: "chainsaw", quantity: 1 },
      { itemId: "poison", quantity: 4 },
      { itemId: "lockpick", quantity: 2 },
      { itemId: "binoculars", quantity: 2 },
      { itemId: "walkie_talkie", quantity: 1 },
      { itemId: "zarkans", quantity: 2 },
    ],
  },
  [LocalizationType.Hospital]: {
    sprite: "modern_largeBuilding.png",
    localizationType: LocalizationType.Hospital,
    specialActionIds: [ActionLibrary.recover.id],
    walkable: true,
    numberMin: 1,
    numberMax: 1,
    startingItems: [
      { itemId: "food", quantity: 4 },
      { itemId: "drink", quantity: 2 },
      { itemId: "bandage", quantity: 4 },
      { itemId: "medicine", quantity: 3 },
      { itemId: "antidote", quantity: 7 },
      { itemId: "spike", quantity: 3 },
      { itemId: "knife", quantity: 2 },
      { itemId: "chemical_weapon", quantity: 1 },
      { itemId: "poison", quantity: 2 },
      { itemId: "virus", quantity: 1 },
      { itemId: "vaccine", quantity: 1 },
      { itemId: "zarkans", quantity: 2 },
    ],
  },
  [LocalizationType.Workshop]: {
    sprite: "medieval_blacksmith.png",
    localizationType: LocalizationType.Workshop,
    specialActionIds: [ActionLibrary.fabricate.id],
    walkable: true,
    numberMin: 1,
    numberMax: 1,
    startingItems: [
      { itemId: "wood", quantity: 6 },
      { itemId: "spike", quantity: 6 },
      { itemId: "knife", quantity: 1 },
      { itemId: "bat", quantity: 2 },
      { itemId: "chainsaw", quantity: 1 },
      { itemId: "molotov", quantity: 2 },
      { itemId: "bullet", quantity: 3 },
      { itemId: "nails", quantity: 4 },
      { itemId: "zarkans", quantity: 5 },
    ],
  },
  [LocalizationType.Security]: {
    sprite: "military_turretMedium.png",
    localizationType: LocalizationType.Security,
    specialActionIds: [ActionLibrary.activate_cameras.id],
    walkable: true,
    numberMin: 1,
    numberMax: 1,
    startingItems: [
      { itemId: "drink", quantity: 2 },
      { itemId: "bulletproof_vest", quantity: 1 },
      { itemId: "pistol", quantity: 3 },
      { itemId: "bullet", quantity: 4 },
      { itemId: "trap", quantity: 4 },
      { itemId: "silencer", quantity: 3 },
      { itemId: "tracker", quantity: 6 },
      { itemId: "binoculars", quantity: 3 },
      { itemId: "walkie_talkie", quantity: 1 },
      { itemId: "zarkans", quantity: 3 },
    ],
  },
  [LocalizationType.GasStation]: {
    sprite: "modern_petrol.png",
    localizationType: LocalizationType.GasStation,
    specialActionIds: [ActionLibrary.refuel.id],
    walkable: true,
    numberMin: 1,
    numberMax: 1,
    startingItems: [
      { itemId: "drink", quantity: 5 },
      { itemId: "food", quantity: 1 },
      { itemId: "bandage", quantity: 1 },
      { itemId: "wood", quantity: 2 },
      { itemId: "chainsaw", quantity: 1 },
      { itemId: "molotov", quantity: 7 },
      { itemId: "fuel", quantity: 6 },
      { itemId: "nails", quantity: 1 },
      { itemId: "walkie_talkie", quantity: 1 },
      { itemId: "zarkans", quantity: 5 },
    ],
  },
  [LocalizationType.Market]: {
    sprite: "modern_cornerShop.png",
    localizationType: LocalizationType.Market,
    specialActionIds: [ActionLibrary.black_market_trade.id],
    walkable: true,
    numberMin: 1,
    numberMax: 1,
    startingItems: [
      { itemId: "drink", quantity: 1 },
      { itemId: "medicine", quantity: 2 },
      { itemId: "bulletproof_vest", quantity: 1 },
      { itemId: "chainsaw", quantity: 1 },
      { itemId: "harpoon", quantity: 5 },
      { itemId: "arrow", quantity: 3 },
      { itemId: "pistol", quantity: 3 },
      { itemId: "bullet", quantity: 2 },
      { itemId: "chemical_weapon", quantity: 3 },
      { itemId: "trap", quantity: 3 },
      { itemId: "c4", quantity: 3 },
      { itemId: "fuel", quantity: 2 },
      { itemId: "silencer", quantity: 1 },
      { itemId: "binoculars", quantity: 1 },
      { itemId: "walkie_talkie", quantity: 2 },
      { itemId: "tracker", quantity: 4 },
      { itemId: "zarkans", quantity: 3 },
    ],
  },
  [LocalizationType.Restaurant]: {
    sprite: "western_saloon.png",
    localizationType: LocalizationType.Restaurant,
    specialActionIds: [ActionLibrary.breakfast.id],
    walkable: true,
    numberMin: 1,
    numberMax: 1,
    startingItems: [
      { itemId: "drink", quantity: 7 },
      { itemId: "food", quantity: 7 },
      { itemId: "antidote", quantity: 2 },
      { itemId: "wood", quantity: 2 },
      { itemId: "knife", quantity: 3 },
      { itemId: "bat", quantity: 1 },
      { itemId: "poison", quantity: 2 },
      { itemId: "molotov", quantity: 3 },
      { itemId: "zarkans", quantity: 3 },
    ],
  },
  [LocalizationType.Road]: {
    sprite: "dirt_02.png",
    localizationType: LocalizationType.Road,
    walkable: true,
    numberMin: 0,
    numberMax: -1,
    startingItems: [
      { itemId: "wood", quantity: 1 },
      { itemId: "spike", quantity: 5 },
      { itemId: "fuel", quantity: 1 },
      { itemId: "zarkans", quantity: 3 },
    ],
  },
  [LocalizationType.Path]: {
    sprite: "grass_02.png",
    localizationType: LocalizationType.Path,
    walkable: true,
    numberMin: 0,
    numberMax: -1,
    startingItems: [
      { itemId: "food", quantity: 2 },
      { itemId: "wood", quantity: 8 },
    ],
  },
  [LocalizationType.Alley]: {
    sprite: "stone_04.png",
    localizationType: LocalizationType.Alley,
    walkable: true,
    numberMin: 0,
    numberMax: -1,
    startingItems: [
      { itemId: "spike", quantity: 1 },
      { itemId: "bottle", quantity: 9 },
    ],
  },
};
