import { ItemCategory, type ItemLibraryDefinition } from "./Item";

export const ItemLibrary: ItemLibraryDefinition = {
  bottle: {
    id: "bottle",
    name: "Botella",
    category: ItemCategory.Material,
    sprite: "Items/empty_bottle.png",
    weapon: false,
    consumable: false,
    weight: 1,
    description:
      "Recipiente vacío que puede combinarse con combustible para elaborar un cóctel molotov.",
    tags: ["Component", "Crafting"],
  },
  drink: {
    id: "drink",
    name: "Bebida",
    category: ItemCategory.Consumable,
    sprite: "Items/water_bottle.png",
    weapon: false,
    consumable: true,
    weight: 3,
    description:
      "Recupera 12 puntos de esfuerzo y deja una botella vacía tras su consumo.",
    sellValue: 2,
    notes: ["Al usarla se obtiene una botella."],
    tags: ["Energy"],
  },
  food: {
    id: "food",
    name: "Comida",
    category: ItemCategory.Consumable,
    sprite: "Items/food.png",
    weapon: false,
    consumable: true,
    weight: 3,
    description: "Recupera 20 puntos de esfuerzo.",
    sellValue: 3,
    tags: ["Energy"],
  },
  bandage: {
    id: "bandage",
    name: "Venda",
    category: ItemCategory.Medical,
    sprite: "Items/bandages.png",
    weapon: false,
    consumable: true,
    weight: 2,
    description:
      "Recupera 5 puntos de vida y puede aplicarse a otro personaje.",
    sellValue: 3,
    tags: ["Healing"],
  },
  medicine: {
    id: "medicine",
    name: "Medicamento",
    category: ItemCategory.Medical,
    sprite: "Board Game Icons/flask_half.png",
    weapon: false,
    consumable: true,
    weight: 1,
    description: "Recupera 8 puntos de vida y puede compartirse con aliados.",
    sellValue: 5,
    tags: ["Healing"],
  },
  antidote: {
    id: "antidote",
    name: "Antídoto",
    category: ItemCategory.Medical,
    sprite: "Board Game Icons/flask_empty.png",
    weapon: false,
    consumable: true,
    weight: 2,
    description:
      "Cura una intoxicación al aplicarse sobre un personaje en la misma localización.",
    sellValue: 2,
    tags: ["Healing", "Status"],
  },
  bulletproof_vest: {
    id: "bulletproof_vest",
    name: "Chaleco antibalas",
    category: ItemCategory.Equipment,
    sprite: "Board Game Icons/shield.png",
    weapon: false,
    consumable: false,
    weight: 5,
    description:
      "Reduce en 1 el daño recibido y en 3 si procede de balas o flechas. No protege frente a fuego, veneno, virus, motosierra ni arma química.",
    sellValue: 20,
    notes: ["No se puede robar mientras está equipado."],
    tags: ["Protective", "Wearable"],
  },
  bandolier: {
    id: "bandolier",
    name: "Bandolera",
    category: ItemCategory.Equipment,
    sprite: "Items/backpack.png",
    weapon: false,
    consumable: false,
    weight: 0,
    description: "Aumenta la capacidad máxima de carga en 5 unidades.",
    sellValue: 4,
    tags: ["Wearable", "Storage"],
  },
  wood: {
    id: "wood",
    name: "Madera",
    category: ItemCategory.Material,
    sprite: "Board Game Icons/resource_wood.png",
    weapon: false,
    consumable: false,
    weight: 1,
    description:
      "Materia prima para fabricar o manipular armas y otros objetos.",
    sellValue: 0,
    tags: ["Component", "Crafting"],
  },
  spike: {
    id: "spike",
    name: "Pincho",
    category: ItemCategory.Material,
    sprite: "Items/spike.png",
    weapon: false,
    consumable: false,
    weight: 1,
    description:
      "Pieza punzante usada como componente en la creación de armas.",
    sellValue: 0,
    tags: ["Component", "Crafting"],
  },
  knife: {
    id: "knife",
    name: "Cuchillo",
    category: ItemCategory.Weapon,
    sprite: "Items/knife.png",
    weapon: true,
    consumable: false,
    weight: 3,
    description:
      "Ataque cuerpo a cuerpo que inflige 4 puntos de vida al objetivo.",
    sellValue: 2,
    recipes: ["Manipular: Madera + 2 Pinchos"],
    tags: ["Melee"],
  },
  bat: {
    id: "bat",
    name: "Bate",
    category: ItemCategory.Weapon,
    sprite: "Board Game Icons/hand.png",
    weapon: true,
    consumable: false,
    weight: 4,
    description:
      "Golpea a todos los personajes de la localización causando 5 puntos de vida.",
    sellValue: 3,
    recipes: ["Manipular: 4 Madera"],
    tags: ["Melee", "Area"],
  },
  nail_bat: {
    id: "nail_bat",
    name: "Bate con clavos",
    category: ItemCategory.Weapon,
    sprite: "Board Game Icons/dice_sword.png",
    weapon: true,
    consumable: false,
    weight: 6,
    description:
      "Versión reforzada que inflige 7 puntos de vida a todos los presentes en la localización.",
    sellValue: 5,
    recipes: ["Manipular: Bate + 2 Clavos"],
    tags: ["Melee", "Area"],
  },
  axe: {
    id: "axe",
    name: "Hacha",
    category: ItemCategory.Weapon,
    sprite: "Board Game Icons/sword.png",
    weapon: true,
    consumable: false,
    weight: 5,
    description:
      "Arma cuerpo a cuerpo que reduce 8 puntos de vida al objetivo.",
    sellValue: 4,
    recipes: ["Manipular: 3 Madera + 2 Pinchos"],
    tags: ["Melee"],
  },
  chainsaw: {
    id: "chainsaw",
    name: "Motosierra",
    category: ItemCategory.Weapon,
    sprite: "Items/chainsaw.png",
    weapon: true,
    consumable: false,
    weight: 5,
    description:
      "Mata al objetivo al atacar. Debe arrancarse gastando combustible y suena en la localización.",
    sellValue: 5,
    notes: ["Requiere combustible para permanecer encendida durante 5 turnos."],
    tags: ["Melee"],
  },
  molotov: {
    id: "molotov",
    name: "Molotov",
    category: ItemCategory.Weapon,
    sprite: "Board Game Icons/fire.png",
    weapon: true,
    consumable: true,
    weight: 3,
    description:
      "Cóctel incendiario que inflige 4 puntos de vida al impactar y puede lanzar fuego a distancia.",
    sellValue: 2,
    recipes: ["Manipular: Botella + Combustible"],
    tags: ["Fire", "Explosive"],
  },
  pistol: {
    id: "pistol",
    name: "Pistola",
    category: ItemCategory.Weapon,
    sprite: "Board Game Icons/dice_sword.png",
    weapon: true,
    consumable: false,
    weight: 3,
    description:
      "Arma de fuego que inflige 10 puntos de vida a un objetivo en la misma localización o adyacente. Requiere balas y hace ruido a 1 casilla.",
    sellValue: 2,
    tags: ["Ranged"],
  },
  silencer: {
    id: "silencer",
    name: "Silenciador",
    category: ItemCategory.Tool,
    sprite: "Board Game Icons/token_subtract.png",
    weapon: false,
    consumable: false,
    weight: 1,
    description:
      "Accesorio que permite crear una pistola con silenciador al manipular una pistola.",
    sellValue: 2,
    tags: ["Tool", "Component"],
  },
  suppressed_pistol: {
    id: "suppressed_pistol",
    name: "Pistola con silenciador",
    category: ItemCategory.Weapon,
    sprite: "Board Game Icons/dice_shield.png",
    weapon: true,
    consumable: false,
    weight: 4,
    description:
      "Pistola modificada que inflige 10 puntos de vida sin generar ruido. Requiere balas para disparar.",
    sellValue: 7,
    recipes: ["Manipular: Pistola + Silenciador"],
    tags: ["Ranged"],
  },
  bullet: {
    id: "bullet",
    name: "Bala",
    category: ItemCategory.Material,
    sprite: "Board Game Icons/token_add.png",
    weapon: false,
    consumable: true,
    weight: 1,
    description:
      "Munición necesaria para disparar una pistola. Se consume automáticamente al disparar.",
    sellValue: 2,
    tags: ["Ammo"],
  },
  harpoon: {
    id: "harpoon",
    name: "Arpón",
    category: ItemCategory.Weapon,
    sprite: "Board Game Icons/bow.png",
    weapon: true,
    consumable: false,
    weight: 4,
    description:
      "Dispara a un objetivo infligiendo 7 puntos de vida en la misma localización o 6 a una adyacente sin generar ruido. Requiere flechas.",
    sellValue: 4,
    tags: ["Ranged"],
  },
  arrow: {
    id: "arrow",
    name: "Flecha",
    category: ItemCategory.Material,
    sprite: "Items/arrow.png",
    weapon: false,
    consumable: true,
    weight: 2,
    description:
      "Munición para el arpón. Se utiliza de manera automática al disparar.",
    sellValue: 1,
    recipes: ["Manipular: Madera + Pincho"],
    tags: ["Ammo", "Crafting"],
  },
  chemical_weapon: {
    id: "chemical_weapon",
    name: "Arma química",
    category: ItemCategory.Weapon,
    sprite: "Board Game Icons/skull.png",
    weapon: true,
    consumable: true,
    weight: 6,
    description:
      "Dispositivo químico que reduce 9 puntos de vida a todos los presentes o 11 a un único objetivo y no puede ser esquivado.",
    sellValue: 10,
    tags: ["Explosive", "Status"],
  },
  rocket_launcher: {
    id: "rocket_launcher",
    name: "Lanzacohetes",
    category: ItemCategory.Weapon,
    sprite: "Board Game Icons/exploding.png",
    weapon: true,
    consumable: true,
    weight: 10,
    description:
      "Arma pesada de un solo uso que inflige 20 puntos de vida en la localización objetivo y destruye sus objetos. La explosión es visible desde toda la ciudad.",
    sellValue: 10,
    tags: ["Explosive", "Ranged"],
  },
  trap: {
    id: "trap",
    name: "Trampa",
    category: ItemCategory.Weapon,
    sprite: "Board Game Icons/puzzle.png",
    weapon: true,
    consumable: true,
    weight: 3,
    description:
      "Dispositivo que causa 7 puntos de vida al primer personaje que entra o sale por la entrada vigilada de la localización.",
    sellValue: 3,
    tags: ["Trap"],
  },
  c4: {
    id: "c4",
    name: "Explosivo C4",
    category: ItemCategory.Weapon,
    sprite: "Board Game Icons/exploding_6.png",
    weapon: true,
    consumable: true,
    weight: 4,
    description:
      "Carga explosiva que debe colocarse antes de detonarse a distancia, infligiendo 12 puntos de vida a todos los presentes.",
    sellValue: 5,
    notes: ["La detonación se escucha a dos localizaciones."],
    tags: ["Explosive"],
  },
  detonator: {
    id: "detonator",
    name: "Detonador",
    category: ItemCategory.Tool,
    sprite: "Board Game Icons/spinner_segment.png",
    weapon: false,
    consumable: true,
    weight: 2,
    description:
      "Control remoto necesario para activar un explosivo C4 ya colocado.",
    tags: ["Tool", "Explosive"],
  },
  fuel: {
    id: "fuel",
    name: "Combustible",
    category: ItemCategory.Material,
    sprite: "Board Game Icons/tokens.png",
    weapon: false,
    consumable: true,
    weight: 2,
    description:
      "Recurso versátil para arrancar motosierras, crear incendios con dos o tres unidades o combinarse con una botella para producir un molotov.",
    sellValue: 2,
    tags: ["Component", "Fire"],
  },
  nails: {
    id: "nails",
    name: "Clavos",
    category: ItemCategory.Material,
    sprite: "Board Game Icons/resource_iron.png",
    weapon: false,
    consumable: true,
    weight: 1,
    description:
      "Conjunto de clavos utilizado para reforzar armas o sabotear bicicletas al lanzarlos en una localización.",
    sellValue: 1,
    tags: ["Component", "Crafting"],
  },
  poison: {
    id: "poison",
    name: "Veneno",
    category: ItemCategory.Consumable,
    sprite: "Board Game Icons/skull.png",
    weapon: true,
    consumable: true,
    weight: 1,
    description:
      "Permite envenenar alimentos o armas cuerpo a cuerpo, causando pérdida de vida progresiva y recompensas económicas cuando no es pactado.",
    sellValue: 1,
    tags: ["Status", "Poison"],
  },
  virus: {
    id: "virus",
    name: "Virus",
    category: ItemCategory.Consumable,
    sprite: "Board Game Icons/flask_full.png",
    weapon: true,
    consumable: true,
    weight: 1,
    description:
      "Infecta a un personaje de forma discreta. Cada final de turno los presentes no vacunados pierden 1 punto de vida.",
    sellValue: 3,
    tags: ["Status", "Infection"],
  },
  vaccine: {
    id: "vaccine",
    name: "Vacuna",
    category: ItemCategory.Medical,
    sprite: "Board Game Icons/flask_half.png",
    weapon: false,
    consumable: true,
    weight: 1,
    description:
      "Evita la pérdida de vida al estar en contacto con personajes infectados por virus.",
    sellValue: 3,
    tags: ["Healing", "Status"],
  },
  lockpick: {
    id: "lockpick",
    name: "Ganzúa",
    category: ItemCategory.Tool,
    sprite: "Board Game Icons/lock_open.png",
    weapon: false,
    consumable: false,
    weight: 1,
    description:
      "Reduce en un turno el tiempo necesario para forzar una caja fuerte.",
    sellValue: 2,
    tags: ["Tool"],
  },
  binoculars: {
    id: "binoculars",
    name: "Prismáticos",
    category: ItemCategory.Technology,
    sprite: "Board Game Icons/card_target.png",
    weapon: false,
    consumable: false,
    weight: 2,
    description:
      "Permite ver a los personajes visibles en una localización adyacente y condicionar acciones a distancia.",
    sellValue: 2,
    tags: ["Detection", "Tool"],
  },
  walkie_talkie: {
    id: "walkie_talkie",
    name: "Walkie talkie",
    category: ItemCategory.Technology,
    sprite: "Board Game Icons/token_give.png",
    weapon: false,
    consumable: false,
    weight: 2,
    description:
      "Dispositivo de comunicación que comparte información de aliados autorizados sobre objetos y personajes detectados.",
    sellValue: 2,
    tags: ["Communication", "Tool"],
  },
  tracker: {
    id: "tracker",
    name: "Localizador",
    category: ItemCategory.Technology,
    sprite: "Board Game Icons/token.png",
    weapon: false,
    consumable: true,
    weight: 0,
    description:
      "Transmisor que informa durante seis turnos de la posición de un personaje objetivo, incluso a distancia con apoyo de walkies.",
    sellValue: 1,
    tags: ["Detection", "Tool"],
  },
  zarkans: {
    id: "zarkans",
    name: "Zarkans",
    category: ItemCategory.Special,
    sprite: "Items/zarkan.png",
    weapon: false,
    consumable: false,
    weight: 0,
    description:
      "Moneda oficial de Zarka utilizada para contratar mercenarios, comprar objetos o realizar transferencias. No puede ser robada.",
    tags: ["Currency"],
  },
  bicycle: {
    id: "bicycle",
    name: "Bicicleta",
    category: ItemCategory.Special,
    sprite: "Board Game Icons/pawn_right.png",
    weapon: false,
    consumable: false,
    weight: 0,
    description:
      "Medio de transporte localizado en ciertas casillas que reduce el esfuerzo de desplazamiento a 1 por casilla.",
    notes: [
      "No puede recogerse ni almacenarse.",
      "Se inutiliza si pisa clavos o trampas.",
    ],
    tags: ["Movement"],
  },
  locker: {
    id: "locker",
    name: "Taquilla",
    category: ItemCategory.Special,
    sprite: "Board Game Icons/cards_stack.png",
    weapon: false,
    consumable: false,
    weight: 0,
    description:
      "Almacenamiento seguro presente en todos los edificios donde dejar objetos para su venta en turnos múltiplos de cinco.",
    notes: [
      "El alcalde recoge los objetos y entrega los zarkans cada cinco turnos.",
    ],
    tags: ["Storage", "Structure"],
  },
  safe: {
    id: "safe",
    name: "Caja fuerte",
    category: ItemCategory.Special,
    sprite: "Board Game Icons/lock_closed.png",
    weapon: false,
    consumable: false,
    weight: 0,
    description:
      "Contenedor con botín oculto en cada edificio. Requiere ser buscada y forzada para acceder a su contenido.",
    tags: ["Storage", "Structure"],
  },
  corpse: {
    id: "corpse",
    name: "Cadáver",
    category: ItemCategory.Special,
    sprite: "Board Game Icons/character_remove.png",
    weapon: false,
    consumable: false,
    weight: 0,
    description:
      "Restos de un jugador fallecido que conservan sus objetos y contienen hasta cuatro raciones comestibles para caníbales o hambrientos.",
    notes: [
      "No se detecta desde otras localizaciones.",
      "Otorga 20 de esfuerzo y resta 1 de vida al consumirse cada ración.",
    ],
    tags: ["Corpse", "Storage"],
  },
};
